package graphs;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */


import java.util.HashSet;

public class WeightedDirectionalGraph {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) throws Exception{
        System.out.println(new App().getGreeting());

        Graph friends = new Graph();
        friends.addNode("Nicholas");
        friends.addNode("Ginger");
        friends.addNode("Snowdrop");
        friends.addNode("Rufus");

        friends.addEdge("Nicholas", "Ginger", 99);
        friends.addEdge("Ginger", "Nicholas", 99);
        friends.addEdge("Nicholas", "Snowdrop", 99);
        friends.addEdge("Snowdrop", "Nicholas", 30);
        friends.addEdge("Nicholas", "Rufus", 42);
        friends.addEdge("Rufus", "Nicholas", 68);
        friends.addEdge("Rufus", "Ginger", 103);
        friends.addEdge("Ginger", "Rufus", 120);
        friends.addEdge("Ginger", "Snowdrop", 72);


        System.out.println(friends);



    }

    public static class Graph {
        public HashSet<Node> vertexes = new HashSet<>();

        public Graph(){}

        public String toString(){
            StringBuilder output = new StringBuilder();
            // Nicholas | Ginger(99), Snowdrop(99), Rufus(42) \n
            for(Node vertex : vertexes){
                output.append(vertex.value);
                output.append(" | ");
                for(Edge e : vertex.neighbors){
                    output.append(
                            String.format("%s(%d), ", e.destination.value, e.loveWeight)
                            ); // %s string standin, %d is digit standin
                }
                output.append("\n");
            }
            return output.toString();
            // Snowdrop | Nicholas
            // Ginger | Nicholas, Rufus
        }

        public int addNode(String value){ // data structure's public methods should not talk about Nodes or require them
            Node newNode = new Node(value);
            vertexes.add(newNode);
            return vertexes.size();
        }

        public void addEdge(String one, String two, int love) throws Exception {
            Node origin = null;
            Node destination = null;
            for(Node node : vertexes){
                if(node.value.equals(one)){
                    origin = node;
                }
                if(node.value.equals(two)){
                    destination = node;
                }
            }

            if(origin == null || destination == null){
                throw new Exception("that node is not there");
            }

            Edge edge = new Edge(origin, destination, love);
            origin.addEdge(edge); // hey Vertex one, you need to keep track of who you know

            // TODO: remove adding the edge to destination to turn it into a directed graph

        }



    }

    public static class Node {
        public String value;
        HashSet<Edge> neighbors = new HashSet<>();

        public Node(String value){
            this.value = value;
        }

        public void addEdge(Edge edge){
            this.neighbors.add(edge);
        }

        public HashSet<Node> getNeighbors(){
            HashSet<Node> allMyUniqueNeighbors = new HashSet<>();
            for(Edge edge : neighbors){
                if(!edge.origin.equals(this)){ // If the node stored in this edge is not me, it is my neighbor
                    allMyUniqueNeighbors.add(edge.origin);
                }
                if(!edge.destination.equals(this)){
                    // samesies, because every edge has me and another node, but I don;t know whether the first or second is actually me
                    allMyUniqueNeighbors.add(edge.destination);
                }
            }
            return allMyUniqueNeighbors;
        }
    }

    public static class Edge {
        int loveWeight;
        Node origin;
        Node destination;

        public Edge(Node origin, Node destination, int loveWeight) {
            this.origin = origin;
            this.destination = destination;
            this.loveWeight = loveWeight;
        }
    }
}


